services:
  - type: web
    name: pointx-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT wsgi:application"
    envVars:
      - key: FLASK_ENV
        value: production